[package]
name = "talk_code"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.12.1", features = ["serde", "with-axum"] }
axum = "0.7.7"
tokio = { version = "1.41.1", features = ["full"] }
